module.exports={
    devServe:{
        port:8001,
        open:true,
        https:false,
        host:"localhost",
    },
    lintOnSave:false,
    outputDir:"dist2",
    assetsDir:"assets",
    indexPath:"out/index.html",
    productionSourceMap:false,
};